### ISSUE TITLE
Error: Dynamic require of "workbox-build" is not supported

### ISSUE THREAD

**Issue by RodrigoBertotti** [anse-app/anse#100]
### How is Anse deployed?

Vercel

### Describe the bug

I got this error when trying to deploy to Vercel, does anyone know what can be?

Thank you!

```
error   Dynamic require of "workbox-build" is not supported
  File:
    /vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:6:9
  Code:
    5 |     return require.apply(this, arguments);
    > 6 |   throw Error('Dynamic require of "' + x + '" is not supported');
        |         ^
      7 | });
      9 | // src/context.ts
  Stacktrace:
Error: Dynamic require of "workbox-build" is not supported
    at file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:6:9
    at loadWorkboxBuild (file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:268:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateServiceWorker (file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:301:26)
    at async _generateSW (file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:471:5)
    at async Object.handler (file:///vercel/path0/node_modules/vite-plugin-pwa/dist/index.js:602:11)
    at async PluginDriver.hookParallel (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:25234:17)
    at async Object.close (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:26486:13)
    at async Module.build (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46487:13)
    at async clientBuild (file:///vercel/path0/node_modules/astro/dist/core/build/static-build.js:224:23)
    at async viteBuild (file:///vercel/path0/node_modules/astro/dist/core/build/static-build.js:71:24)
    at async AstroBuilder.build (file:///vercel/path0/node_modules/astro/dist/core/build/index.js:117:27)
    at async AstroBuilder.run (file:///vercel/path0/node_modules/astro/dist/core/build/index.js:149:7)
    at async build (file:///vercel/path0/node_modules/astro/dist/core/build/index.js:37:3)
    at async runCommand (file:///vercel/path0/node_modules/astro/dist/cli/index.js:170:14)
    at async cli (file:///vercel/path0/node_modules/astro/dist/cli/index.js:211:5)
Error: Command "OUTPUT=vercel astro build" exited with 1
```

Command "OUTPUT=vercel astro build" exited with 1

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by RodrigoBertotti** [comment]
I fixed this by going to the Vercel project > **Build & Development Settings** > **Project Settings** > and I overrided the **Install Command** with `npm install` only

After that, if someone still gets the error `Can't resolve 'fs' error`, [then do this](https://stackoverflow.com/a/62011612/4508758)
