### ISSUE TITLE
Redepoly failed to Vercel

### ISSUE THREAD

**Issue by heiha100** [anse-app/anse#117]
### How is Anse deployed?

Vercel

### Describe the bug

The first deployment was successful with [commit](https://github.com/heiha100/anse/commit/af15158f2ddf85d4a5697bfd47df0ddc07896d8a), but the redeployment triggered by commits consistently fails.

### Console Logs

[15:57:16.694] Running build in Washington, D.C., USA (East) – iad1
[15:57:16.812] Cloning github.com/heiha100/anse (Branch: main, Commit: fbd4fb2)
[15:57:16.821] Skipping build cache, deployment was triggered without cache.
[15:57:17.127] Cloning completed: 314.024ms
[15:57:17.349] Running "vercel build"
[15:57:17.833] Vercel CLI 33.0.1
[15:57:19.411] Running "install" command: ` pnpm install`...
[15:57:20.031] Progress: resolved 1, reused 0, downloaded 0, added 0
[15:57:21.033] Progress: resolved 21, reused 0, downloaded 14, added 0
[15:57:22.033] Progress: resolved 42, reused 0, downloaded 30, added 0
[15:57:23.032] Progress: resolved 72, reused 0, downloaded 69, added 0
[15:57:24.034] Progress: resolved 98, reused 0, downloaded 89, added 0
[15:57:25.042] Progress: resolved 126, reused 0, downloaded 114, added 0
[15:57:26.118] Progress: resolved 206, reused 0, downloaded 192, added 0
[15:57:27.119] Progress: resolved 259, reused 0, downloaded 236, added 0
[15:57:27.156]  WARN  deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
[15:57:28.129] Progress: resolved 323, reused 0, downloaded 288, added 0
[15:57:29.151] Progress: resolved 361, reused 0, downloaded 333, added 0
[15:57:30.150] Progress: resolved 440, reused 0, downloaded 366, added 0
[15:57:31.151] Progress: resolved 554, reused 0, downloaded 468, added 0
[15:57:32.154] Progress: resolved 664, reused 0, downloaded 569, added 0
[15:57:33.164] Progress: resolved 760, reused 0, downloaded 658, added 0
[15:57:34.170] Progress: resolved 829, reused 0, downloaded 724, added 0
[15:57:35.176] Progress: resolved 933, reused 0, downloaded 803, added 0
[15:57:35.862]  WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[15:57:36.180] Progress: resolved 1045, reused 0, downloaded 911, added 0
[15:57:37.181] Progress: resolved 1108, reused 0, downloaded 973, added 0
[15:57:38.205] Progress: resolved 1191, reused 0, downloaded 1045, added 0
[15:57:39.207] Progress: resolved 1325, reused 0, downloaded 1170, added 0
[15:57:40.206] Progress: resolved 1397, reused 0, downloaded 1304, added 0
[15:57:41.202] Packages: +1313
[15:57:41.203] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[15:57:41.225] Progress: resolved 1414, reused 0, downloaded 1313, added 0
[15:57:41.615] Packages are cloned from the content-addressable store to the virtual store.
[15:57:41.615]   Content-addressable store is at: /vercel/.pnpm-store/v3
[15:57:41.615]   Virtual store is at:             node_modules/.pnpm
[15:57:42.227] Progress: resolved 1414, reused 0, downloaded 1316, added 219
[15:57:43.289] Progress: resolved 1414, reused 0, downloaded 1317, added 768
[15:57:44.316] Progress: resolved 1414, reused 0, downloaded 1317, added 1313, done
[15:57:44.630] .../esbuild@0.15.18/node_modules/esbuild postinstall$ node install.js
[15:57:44.631] .../esbuild@0.18.20/node_modules/esbuild postinstall$ node install.js
[15:57:44.633] .../esbuild@0.19.10/node_modules/esbuild postinstall$ node install.js
[15:57:44.633] .../esbuild@0.17.19/node_modules/esbuild postinstall$ node install.js
[15:57:44.842] .../esbuild@0.15.18/node_modules/esbuild postinstall: Done
[15:57:44.849] .../esbuild@0.18.20/node_modules/esbuild postinstall: Done
[15:57:44.905] .../esbuild@0.19.10/node_modules/esbuild postinstall: Done
[15:57:44.928] .../esbuild@0.17.19/node_modules/esbuild postinstall: Done
[15:57:47.305] 
[15:57:47.306] dependencies:
[15:57:47.306] + @astrojs/compiler 2.3.4
[15:57:47.306] + @astrojs/netlify 2.3.0 (4.0.1 is available)
[15:57:47.306] + @astrojs/node 5.3.6 (7.0.2 is available)
[15:57:47.306] + @astrojs/solid-js 2.2.1 (3.0.2 is available)
[15:57:47.306] + @astrojs/vercel 3.8.2 (6.1.0 is available)
[15:57:47.306] + @babel/core 7.23.6
[15:57:47.306] + @mapbox/rehype-prism 0.8.0 (0.9.0 is available)
[15:57:47.306] + @nanostores/solid 0.4.2
[15:57:47.306] + @solid-primitives/clipboard 1.5.7
[15:57:47.306] + @solid-primitives/event-listener 2.3.0
[15:57:47.307] + @solid-primitives/keyboard 1.2.5
[15:57:47.307] + @solid-primitives/scheduled 1.4.1
[15:57:47.307] + @solid-primitives/scroll 2.0.20
[15:57:47.307] + @unocss/reset 0.53.6 (0.58.0 is available)
[15:57:47.307] + @zag-js/checkbox 0.10.5 (0.31.1 is available)
[15:57:47.307] + @zag-js/dialog 0.10.5 (0.31.1 is available)
[15:57:47.307] + @zag-js/menu 0.10.5 (0.31.1 is available)
[15:57:47.307] + @zag-js/select 0.10.5 (0.31.1 is available)
[15:57:47.307] + @zag-js/slider 0.10.5 (0.31.1 is available)
[15:57:47.308] + @zag-js/solid 0.10.5 (0.31.1 is available)
[15:57:47.308] + @zag-js/switch 0.10.5 (0.31.1 is available)
[15:57:47.308] + @zag-js/tabs 0.10.5 (0.31.1 is available)
[15:57:47.308] + @zag-js/toast 0.10.5 (0.31.1 is available)
[15:57:47.308] + @zag-js/toggle 0.10.5 (0.19.1 is available)
[15:57:47.308] + @zag-js/tooltip 0.10.5 (0.31.1 is available)
[15:57:47.308] + acorn 8.11.2
[15:57:47.308] + ajv 8.12.0
[15:57:47.308] + astro 2.10.15 (4.0.7 is available)
[15:57:47.308] + browserslist 4.22.2
[15:57:47.309] + bumpp 9.2.1
[15:57:47.309] + destr 2.0.2
[15:57:47.309] + eslint 8.56.0
[15:57:47.309] + eslint-plugin-import 2.29.1
[15:57:47.309] + eslint-plugin-n 16.5.0
[15:57:47.309] + eslint-plugin-promise 6.1.1
[15:57:47.309] + eventsource-parser 1.1.1
[15:57:47.309] + idb-keyval 6.2.1
[15:57:47.309] + js-sha256 0.9.0 (0.10.1 is available)
[15:57:47.309] + katex 0.16.9
[15:57:47.310] + nanostores 0.9.5
[15:57:47.310] + postcss 8.4.32
[15:57:47.310] + prism-theme-vars 0.2.4
[15:57:47.310] + react 18.2.0
[15:57:47.310] + rehype-katex 6.0.3 (7.0.0 is available)
[15:57:47.310] + rehype-stringify 9.0.4 (10.0.0 is available)
[15:57:47.310] + remark-gfm 3.0.1 (4.0.0 is available)
[15:57:47.310] + remark-math 5.1.1 (6.0.0 is available)
[15:57:47.310] + remark-parse 10.0.2 (11.0.0 is available)
[15:57:47.310] + remark-rehype 10.1.0 (11.0.0 is available)
[15:57:47.311] + rollup 2.79.1 (4.9.1 is available)
[15:57:47.311] + solid-emoji-picker 0.2.1
[15:57:47.311] + solid-js 1.7.7 (1.8.7 is available)
[15:57:47.311] + solid-transition-group 0.2.3
[15:57:47.311] + typescript 5.3.3
[15:57:47.311] + unified 10.1.2 (11.0.4 is available)
[15:57:47.311] + vite 5.0.0-beta.20 (5.0.10 is available)
[15:57:47.311] + workbox-build 7.0.0
[15:57:47.311] + workbox-window 7.0.0
[15:57:47.311] 
[15:57:47.312] devDependencies:
[15:57:47.312] + @evan-yang/eslint-config 1.0.9
[15:57:47.312] + @iconify-json/carbon 1.1.27
[15:57:47.312] + @iconify-json/simple-icons 1.1.85
[15:57:47.312] + @types/mapbox__rehype-prism 0.8.3
[15:57:47.312] + @typescript-eslint/parser 5.62.0 (6.15.0 is available)
[15:57:47.312] + @vite-pwa/astro 0.1.6 (0.2.0 is available)
[15:57:47.312] + eslint-plugin-astro 0.27.2 (0.31.0 is available)
[15:57:47.312] + html2canvas 1.4.1
[15:57:47.312] + punycode 2.3.1
[15:57:47.313] + unocss 0.50.8 (0.58.0 is available)
[15:57:47.313] + vite-plugin-pwa 0.16.7 (0.17.4 is available)
[15:57:47.313] 
[15:57:47.318]  WARN  Issues with peer dependencies found
[15:57:47.319] .
[15:57:47.319] └─┬ unocss
[15:57:47.319]   └─┬ @unocss/astro
[15:57:47.319]     └─┬ @unocss/vite
[15:57:47.319]       └── ✕ unmet peer vite@"^2.9.0 || ^3.0.0-0 || ^4.0.0": found 5.0.0-beta.20
[15:57:47.319] 
[15:57:48.954] 07:57:48 AM [content] No content directory found. Skipping type generation.
[15:57:48.955] 07:57:48 AM [build] output target: server
[15:57:48.955] 07:57:48 AM [build] deploy adapter: @astrojs/vercel/edge
[15:57:48.956] 07:57:48 AM [build] Collecting build info...
[15:57:48.956] 07:57:48 AM [build] Completed in 441ms.
[15:57:48.957] 07:57:48 AM [build] Building server entrypoints...
[15:57:52.816] 07:57:52 AM [build] Completed in 3.86s.
[15:57:52.817] 
[15:57:52.817]  building client 
[15:58:01.204] src/components/ui/SettingsApiKey.tsx (7:9) Error when using sourcemap for reporting an error: Can't resolve original location of error.
[15:58:01.206] [31m[vite-plugin-pwa:build] "setProperty" is not exported by "node_modules/.pnpm/solid-js@1.7.7/node_modules/solid-js/web/dist/web.js", imported by "src/components/ui/SettingsApiKey.tsx".[39m
[15:58:01.206] file: [36m/vercel/path0/src/components/ui/SettingsApiKey.tsx:7:9[39m
[15:58:01.206] [33m5: import { className as _$className } from "solid-js/web";
[15:58:01.207] 6: import { runHydrationEvents as _$runHydrationEvents } from "solid-js/web";
[15:58:01.207] 7: import { setProperty as _$setProperty } from "solid-js/web";
[15:58:01.207]             ^
[15:58:01.208] 8: import { effect as _$effect } from "solid-js/web";
[15:58:01.208] 9: import { getNextElement as _$getNextElement } from "solid-js/web";[39m
[15:58:01.332]  error   "setProperty" is not exported by "node_modules/.pnpm/solid-js@1.7.7/node_modules/solid-js/web/dist/web.js", imported by "src/components/ui/SettingsApiKey.tsx".
[15:58:01.332]   File:
[15:58:01.332]     /vercel/path0/src/components/ui/SettingsApiKey.tsx:7:9
[15:58:01.332]   Code:
[15:58:01.332]     5: import { className as _$className } from "solid-js/web";
[15:58:01.332]     6: import { runHydrationEvents as _$runHydrationEvents } from "solid-js/web";
[15:58:01.332]     7: import { setProperty as _$setProperty } from "solid-js/web";
[15:58:01.332]                 ^
[15:58:01.332]     8: import { effect as _$effect } from "solid-js/web";
[15:58:01.332]     9: import { getNextElement as _$getNextElement } from "solid-js/web";
[15:58:01.332]   Stacktrace:
[15:58:01.332] RollupError: "setProperty" is not exported by "node_modules/.pnpm/solid-js@1.7.7/node_modules/solid-js/web/dist/web.js", imported by "src/components/ui/SettingsApiKey.tsx".
[15:58:01.332]     at error (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
[15:58:01.333]     at Module.error (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
[15:58:01.333]     at Module.traceVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
[15:58:01.333]     at ModuleScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
[15:58:01.333]     at ReturnValueScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.334]     at ChildScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.334]     at ReturnValueScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.334]     at ChildScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.334]     at ReturnValueScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.335]     at ChildScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.335]     at ReturnValueScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.335]     at ReturnValueScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.335]     at ChildScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.336]     at ReturnValueScope.findVariable (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
[15:58:01.336]     at Identifier.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
[15:58:01.336]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.336]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
[15:58:01.337]     at ArrowFunctionExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.337]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
[15:58:01.337]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
[15:58:01.337]     at ExpressionStatement.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.337]     at BlockStatement.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
[15:58:01.337]     at ArrowFunctionExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.337]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.337]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
[15:58:01.338]     at LogicalExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.338]     at ArrowFunctionExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.338]     at ReturnStatement.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.338]     at BlockStatement.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
[15:58:01.338]     at ArrowFunctionExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.338]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.338]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
[15:58:01.338]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
[15:58:01.338]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
[15:58:01.338]     at ExpressionStatement.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.338]     at BlockStatement.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
[15:58:01.338]     at ArrowFunctionExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.338]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.338]     at CallExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
[15:58:01.339]     at ReturnStatement.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.339]     at BlockStatement.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
[15:58:01.339]     at ArrowFunctionExpression.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.339]     at ExportDefaultDeclaration.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
[15:58:01.339]     at Program.bind (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
[15:58:01.339]     at Module.bindReferences (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:13741:18)
[15:58:01.339]     at Graph.sortModules (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25853:20)
[15:58:01.339]     at Graph.build (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25737:14)
[15:58:01.339]     at async file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:26706:13
[15:58:01.339]     at async catchUnfinishedHookActions (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
[15:58:01.339]     at async rollupInternal (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:26701:5)
[15:58:01.339] 
[15:58:01.386] Error: Command "OUTPUT=vercel astro build" exited with 1
[15:58:01.866] 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ppxb** [comment]
this issue [#105 ](https://github.com/anse-app/anse/issues/105) may could help you.

**Comment by miguelgargallo** [comment]
Fixed here: https://github.com/anse-app/anse/pull/121
Waiting for approval
